### ISSUE TITLE
MouseControl props update

### ISSUE THREAD

**Issue by CrossTheDev** [flsy/react-mapycz#385]
Controls don't update when props change. 

`MouseControl` is setup with `pan`, `zoom `and `wheel `props and it never changes. You cannot dynamically enable and disable it.

**Comment by CrossTheDev** [comment]
@kolebjak How can I help?

**Comment by kolebjak** [comment]
If you're keen to help, feel free to raise a PR. Unfortunately I don't have a hint for solving this issue - I'll get to it at some point but don't have much time now for coding (there is always time for code reviews).
