### ISSUE TITLE
setting 'baseLayers' has no effect?

### ISSUE THREAD

**Issue by Kukant** [flsy/react-mapycz#467]
Hi all, what should be the effect of setting the baseLayers property? I expected the colours (and some information) of the map to change. 

This is my code for the map:
`<Map
            center={{lat: 49.75234, lng: 16.469189}}
            width={"100%"}
            height={"100%"}
            baseLayers={[BaseLayers.OPHOTO0203]}
            >...`

I tried to set baseLayers to various values, but it always stays the same - TURIST. I would like to have at least the option to change it to BASE, because in my usecase, turist tracks do not make sense.

**Comment by kolebjak** [comment]
@Kukant by looking in the code BaseLayers are most likely broken. I'll do a fix for that asap.

**Comment by Kukant** [comment]
Works now, thanks a lot for the quick response.

**Comment by dominikjasek** [comment]
It doesn't reflect the update when you change `baseLayer` prop.
