### ISSUE TITLE
React.StrictMode causes clustering to print out twice the size of cluster

### ISSUE THREAD

**Issue by Kukant** [flsy/react-mapycz#470]
I am using clustering on my MarkerLayer. I noticed, that when my Map component re-renders multiple times, the marker count doubles. Even though the layer contains only one Marker, it shows as a cluster of two in the map. 

The multiple re-renders were caused by `React.StrictMode`. I noticed this earlier without using StrictMode, but I am not sure what caused it then.  

Here is my simplified code (lets assume this component is inside React.StrictMode):
```
<Map
            center={initialCoordinates}
            zoom={initialZoom}
            width={"100%"}
            height={"100%"}
            baseLayer={BaseLayers.BASE_NEW}
            mapRef={mapRef}
            onEvent={(event, coords) => onMapEvent(event)}>
            <MarkerLayer
                enableClustering={true}
                clusterConfig={{ maxDistance: 50 }}>
                <Marker coords={SY_COORDINATES}/>
            </MarkerLayer>
</Map>
```

**Comment by kolebjak** [comment]
Thanks for reporting this issue, I'll have a look what's wrong.
