### ISSUE TITLE
React v17, v18

### ISSUE THREAD

**Issue by HonzaKopecky** [flsy/react-mapycz#486]
Would it be possible to update the package to support react v17 and v18? Now the dependencies are set to v16 which makes all dependent projects use `--legacy-peer-deps` when installing. I've only used this package for a short period of time but so far it works with React v18 just fine.

Thanks!

**Comment by HonzaKopecky** [comment]
The dependabot actually already proposed the change which passes all checks: https://github.com/flsy/react-mapycz/pull/473

**Comment by HonzaKopecky** [comment]
There is actually an issue, since new version of webpack requires source maps to be shipped with the package. It should be resolvable by including the `src` folder in `files` section of the `package.json`.

**Comment by kolebjak** [comment]
Thanks for the tips, I'll look into these changes asap :)

**Comment by kolebjak** [comment]
Released in https://github.com/flsy/react-mapycz/releases/tag/v1.2.0
